[package]
name = "module-generics"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0", features = ["full", "visit", "visit-mut"]}
quote = "1.0"
proc-macro2 = "1.0"
